# Google credentials and configuration
google_client_id:      YOUR_CLIENT_ID
google_client_secret:  YOUR_CLIENT_SECRET
google_project_id:     tobisports-2018

# options are "mysql", "postgres", "mongodb", or "datastore"
bookshelf_backend: mysql

# configure CloudSQL for MySQL or PostgreSQL backend
cloudsql_connection_name: tobisports-2018:us-central1:mysql1956
cloudsql_database_name: test
cloudsql_user: root
cloudsql_password: cancer56
cloudsql_port: 3306

# configure Mongo backend
mongo_url: YOUR_MONGODB_URL
mongo_database: YOUR_MONGO_DATABASE
mongo_collection: YOUR_MONGO_COLLECTION
